version: '2'
services:
  app:
    image: eidr-connect-test:latest
    entrypoint:
      - /home/meteor/eidr-connect/run-tests.sh
    depends_on:
      - db
    ports:
      - '3001:3001'
  db:
    image: mongo:latest
    volumes:
      - /shared/data/db:/data/db
    ports:
      - '27017:27017'

