version: '2'
services:
  app:
    image: eidr-connect-test:latest
    volumes:
      - /shared:/shared
    depends_on:
      - mongodb
    command: ['bash', '-c', '/home/meteor/eidr-connect/start-test-server.sh --mongo_host=mongodb --is_docker=true']
  mongodb:
    image: mongo:latest
    volumes:
      - /shared/data/db:/data/db

