import { buildAnnotatedIncidentSnippet } from '/imports/ui/annotation'
import { createIncidentReportsFromEnhancements } from '/imports/utils.coffee'

Template.newIncidentFromSelection.onCreated ->
  @annotatedText = =>
    selection = window.getSelection()
    { startOffset, endOffset } = selection.getRangeAt(0)
    selection.anchorNode.textContent.slice(startOffset, endOffset)

Template.newIncidentFromSelection.helpers
  annotatedText: ->
    Template.instance().annotatedText()

Template.newIncidentFromSelection.events
  'mousedown .add-incident-from-selection': (event, instance) ->
    source = instance.data.source
    selection = window.getSelection()
    { startOffset, endOffset } = selection.getRangeAt(0)
    incident = createIncidentReportsFromEnhancements(source.enhancements,
      countAnnotations: [
        textOffsets: [[startOffset, endOffset]]
        text: instance.annotatedText()
      ]
      articleId: source._id
    )[0]
    incident.autogenerated = false
    snippetHtml = buildAnnotatedIncidentSnippet(
      source.enhancements.source.cleanContent.content, incident
    )
    Modal.show 'suggestedIncidentModal',
      articleId: source._id
      incident: incident
      incidentText: Spacebars.SafeString(snippetHtml)
      offCanvasStartPosition: 'top'
      showBackdrop: true

    selection.removeAllRanges()
