import { buildAnnotatedIncidentSnippet } from '/imports/ui/annotation'
import { createIncidentReportsFromEnhancements } from '/imports/utils.coffee'

Template.newIncidentFromSelection.helpers
  annotatedText: ->
    selection = window.getSelection()
    range = selection.getRangeAt(0)
    textOffsets = [range.startOffset, range.endOffset]
    content = selection.anchorNode.textContent
    content.slice(textOffsets[0], textOffsets[1])

Template.newIncidentFromSelection.events
  'mousedown .add-incident-from-selection': (event, instance) ->
    source = instance.data.source
    range = window.getSelection().getRangeAt(0)
    incident = createIncidentReportsFromEnhancements(source.enhancements,
      countAnnotations: [
        textOffsets: [[range.startOffset, range.endOffset]]
      ]
      articleId: source._id
    )[0]
    incident.autogenerated = false
    snippetHtml = buildAnnotatedIncidentSnippet(
      source.enhancements.source.cleanContent.content, incident
    )
    Modal.show 'suggestedIncidentModal',
      articleId: source._id
      incident: incident
      incidentText: Spacebars.SafeString(snippetHtml)
      offCanvasStartPosition: 'top'
      showBackdrop: true

    window.getSelection().removeAllRanges()
