import GeonameSchema from '/imports/schemas/geoname.coffee'

AnnotationSchema = new SimpleSchema
  "text":
    type: String
    optional: true
  "textOffsets":
    type: [Number]
    optional: true

IncidentReportSchema = new SimpleSchema
  _id:
    type: String
    optional: true
  type:
    type: String
    optional: true
  articleId:
    type: String
    optional: true
  addedByUserName:
    type: String
    optional: true
  addedByUserId:
    type: String
    optional: true
  modifiedByUserName:
    type: String
    optional: true
  modifiedByUserId:
    type: String
    optional: true
  modifiedDate:
    type: Date
    optional: true
  addedDate:
    type: Date
    optional: true
  cases:
    type: Number
    optional: true
  deaths:
    type: Number
    optional: true
  specify:
    type: String
    optional: true
  locations:
    type: [GeonameSchema]
    optional: true
  dateRange:
    type: Object
  "dateRange.type":
    type: String
    allowedValues: ["day","precise"]
    optional: true
  "dateRange.start":
    type: Date
    optional: true
  "dateRange.end":
    type: Date
    optional: true
  "dateRange.cumulative":
    type: Boolean
    optional: true
  travelRelated:
    type: Boolean
    optional: true
  approximate:
    type: Boolean
    optional: true
  disease:
    type: String
    optional: true
  resolvedDisease:
    type: Object
    optional: true
  "resolvedDisease.id":
    type: String
    optional: true
  "resolvedDisease.text":
    type: String
    optional: true
  species:
    type: Object
    optional: true
  "species.id":
    type: String
    optional: true
  "species.text":
    type: String
    optional: true
  status:
    type: String
    optional: true
  deleted:
    type: Boolean
    optional: true
  deletedDate:
    type: Date
    optional: true
  accepted:
    type: Boolean
    optional: true
  annotations:
    type: Object
    optional: true
  "annotations.case":
    type: [AnnotationSchema]
    optional: true
  "annotations.date":
    type: [AnnotationSchema]
    optional: true
  "annotations.location":
    type: [AnnotationSchema]
    optional: true
  "annotations.disease":
    type: [AnnotationSchema]
    optional: true
  autogenerated:
    type: Boolean
    optional: true
  url:
    type: String
    optional: true

module.exports = IncidentReportSchema
